------------------------------
--CREATE TABLES
------------------------------
CREATE TABLE PRICE (
	PRICE_LIST INT NOT NULL, 
	CURR VARCHAR(20),
    BRAND_ID INT,
    PRODUCT_ID VARCHAR(20),
    PRICE FLOAT,
    PRIORITY INT,
    END_DATE TIMESTAMP,
    START_DATE TIMESTAMP
);